//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableTasks
    {
        public int Id { get; set; }
        public string TaskFunction { get; set; }
        public Nullable<int> IdTableEstatus { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdTableWorkflow { get; set; }
    
        public virtual tableEstatus tableEstatus { get; set; }
        public virtual tableWorkflow tableWorkflow { get; set; }
    }
}
